CREATE TABLE HDL_Project.`sima_co` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_co.csv";

CREATE TABLE HDL_Project.`sima_no` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_no.csv";

CREATE TABLE HDL_Project.`sima_no2` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_no2.csv";

CREATE TABLE HDL_Project.`sima_nox` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_nox.csv";

CREATE TABLE HDL_Project.`sima_o3` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_o3.csv";

CREATE TABLE HDL_Project.`sima_pm10` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_pm10.csv";

CREATE TABLE HDL_Project.`sima_pm25` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_pm25.csv";

CREATE TABLE HDL_Project.`sima_prs` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_prs.csv";

CREATE TABLE HDL_Project.`sima_rainf` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_rainf.csv";

CREATE TABLE HDL_Project.`sima_rh` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_rh.csv";

CREATE TABLE HDL_Project.`sima_so2` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_so2.csv";

CREATE TABLE HDL_Project.`sima_sr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_sr.csv";

CREATE TABLE HDL_Project.`sima_tout` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_tout.csv";

CREATE TABLE HDL_Project.`sima_wdr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_wdr.csv";

CREATE TABLE HDL_Project.`sima_wsr` (
`datetime` DATETIME NOT NULL
, `SE` FLOAT NULL
, `NE` FLOAT NULL
, `CE` FLOAT NULL
, `NO` INT NULL
, `SO` INT NULL
, `NO2` INT NULL
, `NTE` FLOAT NULL
, `NE2` FLOAT NULL
, `SE2` INT NULL
, `SO2` FLOAT NULL
, `SE3` FLOAT NULL
, `SUR` INT NULL
, `NTE2` INT NULL
, `NE3` FLOAT NULL
) COMMENT = "Source: sima_wsr.csv";

