CREATE VIEW sima_station_SE AS 
Select l0.datetime, l0.CE as co, l1.SE as no, l2.SE as no2, l3.SE as nox, l4.SE as o3, l5.SE as pm10, l6.SE as pm25, l7.SE as prs, l8.SE as rainf, l9.SE as rh, l10.SE as so2, l11.SE as sr, l12.SE as tout, l13.SE as wdr, l14.SE as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_NE AS 
Select l0.datetime, l0.CE as co, l1.NE as no, l2.NE as no2, l3.NE as nox, l4.NE as o3, l5.NE as pm10, l6.NE as pm25, l7.NE as prs, l8.NE as rainf, l9.NE as rh, l10.NE as so2, l11.NE as sr, l12.NE as tout, l13.NE as wdr, l14.NE as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_CE AS 
Select l0.datetime, l0.CE as co, l1.CE as no, l2.CE as no2, l3.CE as nox, l4.CE as o3, l5.CE as pm10, l6.CE as pm25, l7.CE as prs, l8.CE as rainf, l9.CE as rh, l10.CE as so2, l11.CE as sr, l12.CE as tout, l13.CE as wdr, l14.CE as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_NO AS 
Select l0.datetime, l0.CE as co, l1.NO as no, l2.NO as no2, l3.NO as nox, l4.NO as o3, l5.NO as pm10, l6.NO as pm25, l7.NO as prs, l8.NO as rainf, l9.NO as rh, l10.NO as so2, l11.NO as sr, l12.NO as tout, l13.NO as wdr, l14.NO as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_SO AS 
Select l0.datetime, l0.CE as co, l1.SO as no, l2.SO as no2, l3.SO as nox, l4.SO as o3, l5.SO as pm10, l6.SO as pm25, l7.SO as prs, l8.SO as rainf, l9.SO as rh, l10.SO as so2, l11.SO as sr, l12.SO as tout, l13.SO as wdr, l14.SO as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_NO2 AS 
Select l0.datetime, l0.CE as co, l1.NO2 as no, l2.NO2 as no2, l3.NO2 as nox, l4.NO2 as o3, l5.NO2 as pm10, l6.NO2 as pm25, l7.NO2 as prs, l8.NO2 as rainf, l9.NO2 as rh, l10.NO2 as so2, l11.NO2 as sr, l12.NO2 as tout, l13.NO2 as wdr, l14.NO2 as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_NTE AS 
Select l0.datetime, l0.CE as co, l1.NTE as no, l2.NTE as no2, l3.NTE as nox, l4.NTE as o3, l5.NTE as pm10, l6.NTE as pm25, l7.NTE as prs, l8.NTE as rainf, l9.NTE as rh, l10.NTE as so2, l11.NTE as sr, l12.NTE as tout, l13.NTE as wdr, l14.NTE as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_NE2 AS 
Select l0.datetime, l0.CE as co, l1.NE2 as no, l2.NE2 as no2, l3.NE2 as nox, l4.NE2 as o3, l5.NE2 as pm10, l6.NE2 as pm25, l7.NE2 as prs, l8.NE2 as rainf, l9.NE2 as rh, l10.NE2 as so2, l11.NE2 as sr, l12.NE2 as tout, l13.NE2 as wdr, l14.NE2 as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_SE2 AS 
Select l0.datetime, l0.CE as co, l1.SE2 as no, l2.SE2 as no2, l3.SE2 as nox, l4.SE2 as o3, l5.SE2 as pm10, l6.SE2 as pm25, l7.SE2 as prs, l8.SE2 as rainf, l9.SE2 as rh, l10.SE2 as so2, l11.SE2 as sr, l12.SE2 as tout, l13.SE2 as wdr, l14.SE2 as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_SO2 AS 
Select l0.datetime, l0.CE as co, l1.SO2 as no, l2.SO2 as no2, l3.SO2 as nox, l4.SO2 as o3, l5.SO2 as pm10, l6.SO2 as pm25, l7.SO2 as prs, l8.SO2 as rainf, l9.SO2 as rh, l10.SO2 as so2, l11.SO2 as sr, l12.SO2 as tout, l13.SO2 as wdr, l14.SO2 as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_SE3 AS 
Select l0.datetime, l0.CE as co, l1.SE3 as no, l2.SE3 as no2, l3.SE3 as nox, l4.SE3 as o3, l5.SE3 as pm10, l6.SE3 as pm25, l7.SE3 as prs, l8.SE3 as rainf, l9.SE3 as rh, l10.SE3 as so2, l11.SE3 as sr, l12.SE3 as tout, l13.SE3 as wdr, l14.SE3 as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_SUR AS 
Select l0.datetime, l0.CE as co, l1.SUR as no, l2.SUR as no2, l3.SUR as nox, l4.SUR as o3, l5.SUR as pm10, l6.SUR as pm25, l7.SUR as prs, l8.SUR as rainf, l9.SUR as rh, l10.SUR as so2, l11.SUR as sr, l12.SUR as tout, l13.SUR as wdr, l14.SUR as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;

CREATE VIEW sima_station_NTE2 AS 
Select l0.datetime, l0.CE as co, l1.NTE2 as no, l2.NTE2 as no2, l3.NTE2 as nox, l4.NTE2 as o3, l5.NTE2 as pm10, l6.NTE2 as pm25, l7.NTE2 as prs, l8.NTE2 as rainf, l9.NTE2 as rh, l10.NTE2 as so2, l11.NTE2 as sr, l12.NTE2 as tout, l13.NTE2 as wdr, l14.NTE2 as wsr
from sima_co l0  left join sima_no l1 ON l0.datetime = l1.datetime left join sima_no2 l2 ON l0.datetime = l2.datetime left join sima_nox l3 ON l0.datetime = l3.datetime left join sima_o3 l4 ON l0.datetime = l4.datetime left join sima_pm10 l5 ON l0.datetime = l5.datetime left join sima_pm25 l6 ON l0.datetime = l6.datetime left join sima_prs l7 ON l0.datetime = l7.datetime left join sima_rainf l8 ON l0.datetime = l8.datetime left join sima_rh l9 ON l0.datetime = l9.datetime left join sima_so2 l10 ON l0.datetime = l10.datetime left join sima_sr l11 ON l0.datetime = l11.datetime left join sima_tout l12 ON l0.datetime = l12.datetime left join sima_wdr l13 ON l0.datetime = l13.datetime left join sima_wsr l14 ON l0.datetime = l14.datetime;
